# Use the official Neo4j image as a base
FROM neo4j:5.19.0

# Add custom setup commands here, for example:
# COPY plugins/* /plugins/

# Set environment variables if needed
ENV NEO4J_AUTH=neo4j/test12345678

# Expose the necessary ports
EXPOSE 7474 7687
